[package]
name = "SupSubscription"
edition = "2024.beta"

[dependencies]
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/move-stdlib", rev = "framework/testnet", override = true }
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet", override = true }
SupWallet = { local = "../../sup_wallet" }
payment_kit = { git = "https://github.com/MystenLabs/sui-payment-kit.git", rev = "main" }

[addresses]
SupSubscription = "0x0"

[dev-dependencies]

[dev-addresses]
